[Factory]
name = "Metal Casing Supplier" #"Fixing Supplier" or "Gear Supplier" 
frequencyCheck = 20            #seconds

[frepple_info]
URL = "http://localhost:9000"
password = "admin"
user = "admin"

[mqtt_subsciber]
broker = "localhost" #point to the mqtt broker same ad frepple IP address
port = 1883

[[mqtt_subsciber.subscription]]
topic = "MES/#" #the mqtt topic shoestring mqtt broker uses


[[json_message_rewriter.entry]]
topic = "#"
append = true
spec_json = '''{"time":"$.timestamp"}'''
# equivalent
#[json_message_rewriter.entry.spec]
#	time="$.timestamp"


[mqtt_publish]
# mqtt_messege settings 


[[mqtt_publish.customer]]
# customer 1 in chain
name = "Robot Assembly Factory"
address = "129.169.48.176"
port = 1883

[[mqtt_publish.customer]]
# customer 1 in chain
name = "Manual Assembly Factory"
address = "129.169.48.174"
port = 1883
