[Factory]
name = "Design_Studio" #"3D Printing Factory" or "Robot Assembly Factory"
frequencyCheck = 20    #seconds

[frepple_info]
URL = "http://129.169.48.175:9000"
password = "admin"
user = "admin"

[mqtt_subsciber]
broker = "129.169.48.175" #point to the mqtt broker same ad frepple IP address
port = 1883

[[mqtt_subsciber.subscription]]
topic = "MES/#" #the mqtt topic shoestring mqtt broker uses


[[json_message_rewriter.entry]]
topic = "#"
append = true
spec_json = '''{"time":"$.timestamp"}'''
# equivalent
#[json_message_rewriter.entry.spec]
#	time="$.timestamp"


[mqtt_publish]
# mqtt_messege settings 

[[mqtt_publish.supplier]]
# Supplier 1 in chain
name = "Supplier" #ABS material supplier"
address = ""      #"129.169.48.175" "129.169.232.174"
port = 1883

[[mqtt_publish.customer]]
# customer 1 in chain
name = "Robot_Lab"
address = "129.169.48.176"
port = 1883

[[mqtt_publish.customer]]
# customer 1 in chain
name = "Manual_Assembly"
address = "129.169.48.174"
port = 1883
